plugins:
  - jekyll-seo-tag

port: 4001

styles:

remote_theme: kosatyi/sjt

exclude:
  - vendor
  - src

javascript:

baseurl: /localize

navigation: false

projects: true

title: Localize
description: PHP Gettext translation generator from project files
logo: https://i.imgur.com/sbmTP8q.png

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
