remote_theme: kosatyi/sjt

navigation: false
projects: true

baseurl: /localize

brand: localize
title: Localize
description: PHP Gettext translation generator from project files
analytics: UA-37629144-1

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/